name: System monitor (Linux)

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:

jobs:
  system-monitor:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.12"]
        theme: [ "3.5inchTheme2" ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Configure system monitor
      run: |
        # For tests there is no real HW: use simulated LCD mode
        sed -i "/REVISION:/c\  REVISION: SIMU" config.yaml
        
        # Setup selected theme in config.yaml
        echo "Using theme ${{ matrix.theme }}"
        sed -i "/THEME:/c\  THEME: ${{ matrix.theme }}" config.yaml

    - name: Run system monitor for 20 seconds
      run: |
        python3 main.py > output.log 2>&1 &
        sleep 20

    - name: Check output for errors
      run: |
        echo "######## Output : ########"
        cat output.log
        
        if grep -qi "error" output.log; then
          echo "Program failed to run, see output above"
          false
        elif grep -qi "traceback" output.log; then
          echo "Program failed to run, see output above"
          false
        elif grep -qi "exception" output.log; then
          echo "Program failed to run, see output above"
          false
        fi

    - name: Prepare screenshot for archiving
      run: |
        cp screencap.png screenshot-py${{ matrix.python-version }}-${{ matrix.theme }}.png

    - name: Archive a screenshot
      uses: actions/upload-artifact@v4
      with:
        name: screenshot-py${{ matrix.python-version }}-${{ matrix.theme }}
        path: screenshot-*.png